language: php

php:
  - 7.0


before_script:
  - travis encrypt "solosystems:fkX1hFVmmctRBu8f0CsBWeFh" --add notifications.slack
  - mysql -e 'create database travis_test;'
  - cp .env.travis .env
  - composer self-update
  - composer install
  - php artisan key:generate
  - php artisan migrate

script: ./vendor/bin/phpunit