language: php

php:
  - 7.0

notifications:
  slack: solosystems:fkX1hFVmmctRBu8f0CsBWeFh

before_script:
  - mysql -e 'create database travis_test;'
  - cp .env.travis .env
  - composer self-update
  - composer install
  - php artisan key:generate
  - php artisan migrate

script: ./vendor/bin/phpunit